### ISSUE TITLE
1.15.2 aura addons crash due to api change

### ISSUE THREAD

**Issue by SDUBZ** [superaxander/Auraddons#6]
all the details are here
https://github.com/Ellpeck/NaturesAura/issues/109

**Comment by superaxander** [comment]
I'm working on fixing it you can expect a fix to come somewhere in the coming weekend

**Comment by SDUBZ** [comment]
okay thank you

**Comment by goaliejordan** [comment]
any update to this fix?

**Comment by superaxander** [comment]
Yes sorry, I was busy and then I forgot to do it. I'll see if I can find the time this week
